name: root
dependencies:
- _license=1.1=py27_1
- anaconda=2.4.1=np110py27_0
- anaconda-client=1.2.1=py27_0
- cdecimal=2.3=py27_0
- cffi=1.2.1=py27_0
- clyent=1.2.0=py27_0
- colorama=0.3.3=py27_0
- conda=3.19.1=py27_0
- conda-build=1.18.2=py27_0
- conda-env=2.4.5=py27_0
- docutils=0.12=py27_0
- freetype=2.5.5=0
- funcsigs=0.4=py27_0
- ipykernel=4.1.1=py27_0
- ipython=4.0.1=py27_0
- ipython-notebook=4.0.4=py27_0
- ipython-qtconsole=4.0.1=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.0=py27_0
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_1
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.0.3=py27_0
- jupyter_core=4.0.6=py27_0
- libdynd=0.7.0=0
- libpng=1.6.17=0
- libtiff=4.0.6=1
- libxml2=2.9.2=0
- libxslt=1.1.28=2
- llvmlite=0.8.0=py27_0
- lxml=3.4.4=py27_0
- markupsafe=0.23=py27_0
- matplotlib=1.5.0=np110py27_0
- multipledispatch=0.4.8=py27_0
- nbconvert=4.0.0=py27_0
- nbformat=4.0.1=py27_0
- networkx=1.10=py27_0
- node-webkit=0.10.1=0
- notebook=4.0.6=py27_0
- numpy=1.10.1=py27_0
- pandas=0.17.1=np110py27_0
- pyqt=4.11.4=py27_1
- pytables=3.2.2=np110py27_0
- pytest=2.8.1=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- qt=4.8.7=1
- qtconsole=4.1.1=py27_0
- readline=6.2=2
- redis=2.6.9=0
- redis-py=2.10.3=py27_0
- scikit-image=0.11.3=np110py27_0
- scikit-learn=0.17=np110py27_1
- scipy=0.16.0=np110py27_1
- setuptools=19.6.2=py27_0
- statsmodels=0.6.1=np110py27_0
- tk=8.5.18=0

